In [1]:
import pandas as pd

In [2]:
data = pd.read_csv(r'./spam.csv')
data

Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [3]:
missing_values = data.isna().sum()
missing_values

Category    0
Message     0
dtype: int64

In [4]:
x = data.iloc[:,1].values
x

array(['Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...',
       'Ok lar... Joking wif u oni...',
       "Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       ..., 'Pity, * was in mood for that. So...any other suggestions?',
       "The guy did some bitching but I acted like i'd be interested in buying something else next week and he gave it to us for free",
       'Rofl. Its true to its name'], dtype=object)

In [5]:
y = data.iloc[:,0].values
y

array(['ham', 'ham', 'spam', ..., 'ham', 'ham', 'ham'], dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()
y = le.fit_transform(y)
y

array([0, 0, 1, ..., 0, 0, 0])

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
x_test

array(['Storming msg: Wen u lift d phne, u say "HELLO" Do u knw wt is d real meaning of HELLO?? . . . It\'s d name of a girl..! . . . Yes.. And u knw who is dat girl?? "Margaret Hello" She is d girlfrnd f Grahmbell who invnted telphone... . . . . Moral:One can 4get d name of a person, bt not his girlfrnd... G o o d n i g h t . . .@',
       '<Forwarded from 448712404000>Please CALL 08712404000 immediately as there is an urgent message waiting for you.',
       "And also I've sorta blown him off a couple times recently so id rather not text him out of the blue looking for weed",
       ...,
       'I got a call from a landline number. . . I am asked to come to anna nagar . . . I will go in the afternoon',
       '#ERROR!', 'What you doing?how are you?'], dtype=object)

In [11]:
y_test

array([0, 1, 0, ..., 0, 1, 0])

In [12]:
x_train = x_train.tolist()
x_test = x_test.tolist()

In [13]:
x_train = [str(review).lower() for review in x_train]
x_test = [str(review).lower() for review in x_test]

In [14]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [15]:
tf = TfidfVectorizer(max_features=5000)
x_train = tf.fit_transform(x_train)
x_test = tf.transform(x_test)
x_train

<4457x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 56215 stored elements in Compressed Sparse Row format>

In [16]:
x_test

<1115x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 13678 stored elements in Compressed Sparse Row format>

In [17]:
from sklearn.linear_model import LogisticRegression

In [18]:
lr = LogisticRegression()
model = lr.fit(x_train,y_train)
y_prediction = model.predict(x_test)
y_prediction

array([0, 1, 0, ..., 0, 0, 0])

In [20]:
from sklearn.metrics import accuracy_score

In [21]:
print("Logistic Regression accuracy score =",accuracy_score(y_test, y_prediction))

Logistic Regression accuracy score = 0.9713004484304932


In [22]:
from sklearn.metrics import classification_report

In [23]:
print("Logistic Regression Classification Report:",classification_report(y_test, y_prediction))

Logistic Regression Classification Report:               precision    recall  f1-score   support

           0       0.97      1.00      0.98       955
           1       0.98      0.81      0.89       160

    accuracy                           0.97      1115
   macro avg       0.98      0.91      0.94      1115
weighted avg       0.97      0.97      0.97      1115



In [24]:
from sklearn.ensemble import RandomForestClassifier

In [25]:
rfc = RandomForestClassifier()
model2 = rfc.fit(x_train,y_train)
y_prediction2 = model2.predict(x_test)
y_prediction2

array([0, 1, 0, ..., 0, 1, 0])

In [26]:
print("Random Forest Classifier accuracy score =",accuracy_score(y_test, y_prediction2))

Random Forest Classifier accuracy score = 0.9847533632286996


In [27]:
print("Random Forest Classification Report:",classification_report(y_test, y_prediction2))

Random Forest Classification Report:               precision    recall  f1-score   support

           0       0.98      1.00      0.99       955
           1       1.00      0.89      0.94       160

    accuracy                           0.98      1115
   macro avg       0.99      0.95      0.97      1115
weighted avg       0.99      0.98      0.98      1115



In [28]:
from sklearn.ensemble import AdaBoostClassifier

In [29]:
abc = AdaBoostClassifier()
model3 = rfc.fit(x_train,y_train)
y_prediction3 = model3.predict(x_test)
y_prediction3

array([0, 1, 0, ..., 0, 1, 0])

In [30]:
print("AdaBoost Classifier accuracy score =",accuracy_score(y_test, y_prediction3))

AdaBoost Classifier accuracy score = 0.9829596412556054


In [31]:
print("AdaBoost Classifier Report:",classification_report(y_test, y_prediction3))

AdaBoost Classifier Report:               precision    recall  f1-score   support

           0       0.98      1.00      0.99       955
           1       1.00      0.88      0.94       160

    accuracy                           0.98      1115
   macro avg       0.99      0.94      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [32]:
from sklearn.neighbors import KNeighborsClassifier

In [33]:
knn = KNeighborsClassifier()
model4 = knn.fit(x_train,y_train)
y_prediction4 = model4.predict(x_test)
y_prediction4

array([0, 1, 0, ..., 0, 0, 0])

In [34]:
print("knn accuracy score =",accuracy_score(y_test, y_prediction4))

knn accuracy score = 0.9192825112107623


In [36]:
print("knn Classification Report:",classification_report(y_test, y_prediction4))

knn Classification Report:               precision    recall  f1-score   support

           0       0.91      1.00      0.95       955
           1       1.00      0.44      0.61       160

    accuracy                           0.92      1115
   macro avg       0.96      0.72      0.78      1115
weighted avg       0.93      0.92      0.91      1115

